server:
  port: 8080

exchange:
  baseUrl: https://api.valr.com/v1/public

quotes:
  supportedPairs:
    BTCZAR:
      base: BTC
      counter: ZAR
    ETHZAR:
      base: ETH
      counter: ZAR
    USDCZAR:
      base: USDC
      counter: ZAR
  ttlSeconds: 120

brokerage:
  feePercent: 0.015
